language: objective-c
cache: cocoapods
podfile: Inkwell/Podfile
before_install:
- gem install -N cocoapods -v 1.2.1
- pod repo update
- pod install --project-directory=Inkwell
env:
  global:
  - WORKSPACE=Inkwell/Inkwell.xcworkspace
  - SCHEME=Inkwell
matrix:
  include:
  - osx_image: xcode8.2
    env: SDK="iphonesimulator10.2" DESTINATION="name=iPhone 6s,OS=10.2"
  - osx_image: xcode8.3
    env: SDK="iphonesimulator10.3" DESTINATION="name=iPhone 6s,OS=10.3.1"
script:
- set -o pipefail
- xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES | xcpretty
